# YouTube Integration Configuration

youtube:
  # API Configuration
  credentials_file: "config/youtube_credentials.json"
  token_file: "config/youtube_token.json"
  daily_quota: 10000
  
  # Default Video Settings
  defaults:
    privacy_status: "private"  # private, unlisted, public
    category_id: "22"          # People & Blogs
    language: "en"
    default_tags: ["maya", "ai", "automation"]
  
  # Upload Settings
  upload:
    max_file_size_mb: 128000   # 128GB max
    supported_formats: ["mp4", "mov", "avi", "wmv", "flv", "webm"]
    chunk_size_mb: 10          # Upload chunk size
    retry_attempts: 3
    timeout_seconds: 3600      # 1 hour timeout
  
  # Content Moderation
  moderation:
    enabled: true
    spam_threshold: 0.7
    toxicity_threshold: 0.8
    auto_moderate: false       # Require human approval
    blocked_keywords: []
    allowed_domains: []
  
  # Comment Management
  comments:
    auto_reply:
      enabled: true
      reply_threshold: 0.8     # Confidence threshold for auto-replies
      max_replies_per_hour: 50
      max_replies_per_video: 100
      cooldown_minutes: 30     # Cooldown between replies to same user
    
    moderation:
      auto_hide_spam: true
      auto_hide_toxic: true
      require_approval: false
    
    analysis:
      sentiment_analysis: true
      topic_extraction: true
      intent_classification: true
  
  # Content Strategy
  strategy:
    ai_generation:
      enabled: true
      idea_generation: true
      title_optimization: true
      description_enhancement: true
      tag_suggestions: true
      thumbnail_concepts: true
    
    trending:
      monitor_trends: true
      trend_categories: ["technology", "education", "entertainment"]
      update_frequency_hours: 6
    
    scheduling:
      optimal_timing: true
      timezone: "UTC"
      posting_schedule:
        - day: "monday"
          time: "10:00"
        - day: "wednesday" 
          time: "14:00"
        - day: "friday"
          time: "16:00"
  
  # Analytics
  analytics:
    collection:
      enabled: true
      metrics: ["views", "likes", "comments", "shares", "watch_time", "subscribers"]
      retention_days: 365
      update_frequency_hours: 24
    
    reporting:
      daily_summary: true
      weekly_analysis: true
      monthly_strategy: true
      performance_alerts: true
    
    thresholds:
      low_performance_views: 100
      high_performance_views: 10000
      engagement_rate_target: 0.05
  
  # Playlist Management
  playlists:
    auto_organize: true
    categories:
      - name: "Tutorials"
        keywords: ["tutorial", "how-to", "guide"]
      - name: "Reviews"
        keywords: ["review", "comparison", "analysis"]
      - name: "Updates"
        keywords: ["update", "news", "announcement"]
  
  # Safety and Compliance
  safety:
    content_scanning: true
    copyright_check: true
    community_guidelines: true
    advertiser_friendly: true
    
    human_review:
      required_for_upload: false
      required_for_replies: false
      escalation_threshold: 0.9
  
  # Rate Limiting
  rate_limits:
    uploads_per_day: 6
    comments_per_minute: 10
    searches_per_minute: 100
    api_calls_per_minute: 200
    
    backoff:
      initial_delay: 1
      max_delay: 300
      multiplier: 2
  
  # Integration Settings
  integration:
    cerebras:
      enabled: true
      model: "llama3.1-70b"
      max_tokens: 2000
      temperature: 0.7
    
    orchestrator:
      enabled: true
      webhook_url: "http://localhost:8000/webhooks/youtube"
      events: ["upload", "comment", "analytics"]
    
    cross_platform:
      twitter_promotion: true
      content_syndication: false

# Environment-specific overrides
development:
  youtube:
    defaults:
      privacy_status: "private"
    safety:
      human_review:
        required_for_upload: true
        required_for_replies: true

production:
  youtube:
    defaults:
      privacy_status: "public"
    moderation:
      auto_moderate: true
    safety:
      human_review:
        required_for_upload: false
        required_for_replies: false
